name: Build and publish hexdoc-latex

on:
  push:
    branches: "*"
    tags: "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      release:
        description: Release this version
        type: boolean
        default: false
      publish:
        description: Package index to publish to
        type: choice
        options:
          - none
          - PyPI

env:
  PYPI_PACKAGE: hexdoc-latex

permissions:
  contents: read

jobs:
  build:
    uses: hexdoc-dev/hexdoc/.github/workflows/hexdoc-plugin.yml@main
    permissions:
      contents: write
      pages: read
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python-version: "3.11"
      release: |-
        ${{
          github.event_name != 'push' && inputs.release
          || github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install display server
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: xvfb

      - name: Install Nox
        run: pip install nox

      - name: Run Nox
        env:
          GITHUB_PAGES_URL: https://hexcasting.hexxy.media
        run: xvfb-run --auto-servernum nox

  publish-pypi:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: |-
      needs.build.outputs.release == 'true' &&
      (github.event_name == 'push' || inputs.publish == 'PyPI')
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PYPI_PACKAGE }}
    permissions:
      id-token: write
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: hexdoc-build
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
